version: "3.8"
services:
  candycli:
    build: .
    image: candycli:latest
    network_mode: "host" # Use host network so container can access LAN devices directly (Linux only)
    stdin_open: true
    tty: true